development:
  paypal:
    login: "ersandeep0610-facilitator_api1.gmail.com"
    password: "1381692969"
    signature: "AahmysjmaE8KfL4xMF9Hq6mOI2e5AJdf.rAx2Q4TVKW.4xqn9z.K9YMy"

test:
  paypal:
    login: "ersandeep0610-facilitator_api1.gmail.com"
    password: "1381692969"
    signature: "AahmysjmaE8KfL4xMF9Hq6mOI2e5AJdf.rAx2Q4TVKW.4xqn9z.K9YMy"

production:
  paypal:
    login: "ersandeep0610-facilitator_api1.gmail.com"
    password: "1381692969"
    signature: "AahmysjmaE8KfL4xMF9Hq6mOI2e5AJdf.rAx2Q4TVKW.4xqn9z.K9YMy"