# development:
#   host: 192.168.10.200
#   adapter: postgresql
#   encoding: unicode
#   database: TradeLabor
#   pool: 25
#   timeout: 5000
#   username: postgres
#   password: nahtan12

# test:
#   host: 192.168.10.200
#   adapter: postgresql
#   encoding: unicode
#   database: TradeLabor
#   pool: 25
#   timeout: 5000
#   username: postgres
#   password: nahtan12


development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: trade_labor_development
  pool: 5
  username: postgres
  password: 123456

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: trade_labor_test
  pool: 5
  username: postgres
  password: 123456

production:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: trade_labor_production
  pool: 5
  username: postgres
  password: 123456